/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_una_realtime_RtBackupAgent_RtDriverControl */

#ifndef _Included_com_una_realtime_RtBackupAgent_RtDriverControl
#define _Included_com_una_realtime_RtBackupAgent_RtDriverControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_una_realtime_RtBackupAgent_RtDriverControl
 * Method:    QueryLastShutDownStatus
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_una_realtime_RtBackupAgent_RtDriverControl_QueryLastShutDownStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_una_realtime_RtBackupAgent_RtDriverControl
 * Method:    ResetLastShutDownStatus
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_una_realtime_RtBackupAgent_RtDriverControl_ResetLastShutDownStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_una_realtime_RtBackupAgent_RtDriverControl
 * Method:    QueryDriverStatus
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_una_realtime_RtBackupAgent_RtDriverControl_QueryDriverStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_una_realtime_RtBackupAgent_RtDriverControl
 * Method:    AddBackupSet
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_una_realtime_RtBackupAgent_RtDriverControl_AddBackupSet
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_una_realtime_RtBackupAgent_RtDriverControl
 * Method:    AddBackupItems
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_una_realtime_RtBackupAgent_RtDriverControl_AddBackupItems
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_una_realtime_RtBackupAgent_RtDriverControl
 * Method:    DelBackupSet
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_una_realtime_RtBackupAgent_RtDriverControl_DelBackupSet
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_una_realtime_RtBackupAgent_RtDriverControl
 * Method:    DelBackupItems
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_una_realtime_RtBackupAgent_RtDriverControl_DelBackupItems
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_una_realtime_RtBackupAgent_RtDriverControl
 * Method:    DelAllBackup
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_una_realtime_RtBackupAgent_RtDriverControl_DelAllBackup
  (JNIEnv *, jobject);

/*
 * Class:     com_una_realtime_RtBackupAgent_RtDriverControl
 * Method:    ResetError
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_una_realtime_RtBackupAgent_RtDriverControl_ResetError
  (JNIEnv *, jobject);

/*
 * Class:     com_una_realtime_RtBackupAgent_RtDriverControl
 * Method:    Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_una_realtime_RtBackupAgent_RtDriverControl_Release
  (JNIEnv *, jobject);

/*
 * Class:     com_una_realtime_RtBackupAgent_RtDriverControl
 * Method:    SetDriverNotify
 * Signature: (Lcom/una/realtime/RtBackupAgent/RtDriverManager;)V
 */
JNIEXPORT void JNICALL Java_com_una_realtime_RtBackupAgent_RtDriverControl_SetDriverNotify
  (JNIEnv *, jobject, jobject);

void NotifyManagerDriverMessage(jlong jlMessage, jlong jlParam);
#ifdef __cplusplus
}
#endif
#endif
